version: "3.8"
services:
  zap:
    image: owasp/zap2docker-stable
    container_name: "zap"
    ports:
      - 8080:8080
      - 8090:8090
      - 9090:9090
      - 41889:41889

    ## webswing
    command: zap-webswing.sh

    ## headless
    ## command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

  juice-shop:
    image: bkimminich/juice-shop
    container_name: "juice-shop"
    ports:
      - 3000:3000
