version: "3.8"
services:
  zap:
    image: owasp/zap2docker-stable
    container_name: "zap"
    ports:
      - 8080:8080
      - 8090:8090
      - 9090:9090

    ## webswing or headless
    ## webswing
    command: zap-webswing.sh

    ## headless
    ## command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=bkrmeifi3jfne2jkdejf9

  juice-shop:
    image: bkimminich/juice-shop
    container_name: "juice-shop"
    ports:
      - 3000:3000
